#!/usr/bin/env bash

# Update the ICES array in src/ice.rs based on the contents of ice/

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
ice_rs="$project_root/src/ice.rs"
ice_dir="$project_root/ice"

printf '// DO NOT EDIT: generated by scripts/update-ices.rs\n' > "${ice_rs}"
printf 'pub(crate) const ICES: &[(&str, &str)] = &[\n' >> "${ice_rs}"
find "$ice_dir" -maxdepth 1 -name "*.rs" -type f | \
  sort | \
  while read -r rs_file; do
      rs_path="${rs_file#"${project_root}"/}"
      out_path="${rs_path%.rs}.out"
      printf '    ("%s", include_str!("../%s")),\n' "$rs_path" "$out_path" >> "${ice_rs}"
  done
printf '];\n' >> "${ice_rs}"

cargo fmt
